# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-calculate-activity
Version: 30
Release: %mkrel 1
Summary: Calculate activity for Sugar
License: GPLv2+
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Calculate/Calculate-30.tar.bz2

Requires: sugar-toolkit >= 0.85.8

BuildRequires: gettext  
BuildRequires: sugar-toolkit >= 0.85.8

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
The calculate activity provides a generic calculator.
The interface provides the simplest functions directly and should therefore
be easy to usen for the youngest children. However, it does support more
complicated math and variables.

%prep
%setup -q -n Calculate-30


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.Calculate

%clean
rm -rf %{buildroot}

%files -f org.laptop.Calculate.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc NEWS AUTHORS COPYING

