# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-calculate-activity
Version: 28
Release: %mkrel 1
Summary: Calculate activity for Sugar
License: GPLv2+
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Calculate/Calculate-28.tar.bz2

Requires: sugar-toolkit >= 0.83.4

BuildRequires: sugar-toolkit >= 0.83.4
BuildRequires: gettext  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
The calculate activity provides a generic calculator.
The interface provides the simplest functions directly and should therefore
be easy to usen for the youngest children. However, it does support more
complicated math and variables.

%prep
%setup -q -n Calculate-28


%build
python  \
	setup.py \
	build

%install
rm -rf %{buildroot}
[ -f setup.py ] && chmod 0755 setup.py
python  \
	setup.py \
	install \
	--prefix=%{buildroot}/%{_prefix}
%find_lang org.laptop.Calculate

%clean
rm -rf %{buildroot}

%files -f org.laptop.Calculate.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc AUTHORS COPYING NEWS

